import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/manager_dashboard_stats.dart';
import '../models/order_model.dart';

class OrderService {
  final SupabaseClient _client;

  OrderService({SupabaseClient? client})
    : _client = client ?? Supabase.instance.client;

  Future<List<OrderModel>> getOrders(String userId) async {
    final data = await _client
        .from('orders')
        .select(
          '*, items:order_items(*, variant:product_variants(*, product:products(*)))',
        )
        .eq('user_id', userId)
        .order('created_at', ascending: false);
    return data.map((e) => OrderModel.fromMap(e)).toList();
  }

  Future<List<OrderModel>> getAllOrders({String? status}) async {
    var query = _client
        .from('orders')
        .select(
          '*, customer:profiles!orders_user_id_fkey(full_name), items:order_items(*, variant:product_variants(*, product:products(*)))',
        );
    if (status != null && status.isNotEmpty) {
      query = query.eq('status', status);
    }
    final data = await query.order('created_at', ascending: false);
    return data.map((e) => OrderModel.fromMap(e)).toList();
  }

  Future<ManagerDashboardStats> getDashboardStats() async {
    final results = await Future.wait([
      _client.from('orders').select('total,status,created_at'),
      _client.from('products').select('id'),
      _client.from('profiles').select('id,role'),
    ]);

    final orders = List<Map<String, dynamic>>.from(results[0]);
    final products = List<Map<String, dynamic>>.from(results[1]);
    final profiles = List<Map<String, dynamic>>.from(results[2]);
    return ManagerDashboardStats.fromRows(
      orders: orders,
      products: products,
      profiles: profiles,
    );
  }

  Future<OrderModel?> getOrderById(String id) async {
    final data = await _client
        .from('orders')
        .select(
          '*, items:order_items(*, variant:product_variants(*, product:products(*)))',
        )
        .eq('id', id)
        .maybeSingle();
    return data != null ? OrderModel.fromMap(data) : null;
  }

  /// Inserts the order row first, then inserts each order_items row separately.
  /// order_number is auto-generated by the DB — not included in toMap().
  /// Returns the inserted row (with DB-generated order_number) as an OrderModel.
  Future<OrderModel> createOrder(OrderModel order) async {
    final inserted = await _client
        .from('orders')
        .insert(order.toMap())
        .select()
        .single();
    for (final item in order.items) {
      await _client.from('order_items').insert({
        'order_id': order.id,
        ...item.toMap(),
      });
    }
    // The insert response has no 'items' key, so OrderModel.fromMap() would
    // return an empty items list — callers already have the original items
    // from [order], so we only need order_number + other DB-generated fields.
    final saved = OrderModel.fromMap(inserted);
    return OrderModel(
      id: saved.id,
      userId: saved.userId,
      customerName: saved.customerName,
      items: order.items,
      subtotal: saved.subtotal,
      shippingFee: saved.shippingFee,
      total: saved.total,
      status: saved.status,
      address: saved.address,
      latitude: saved.latitude,
      longitude: saved.longitude,
      note: saved.note,
      discountAmount: saved.discountAmount,
      orderNumber: saved.orderNumber,
      paymentMethod: saved.paymentMethod,
      createdAt: saved.createdAt,
      updatedAt: saved.updatedAt,
    );
  }

  Future<void> updateOrderStatus(String orderId, String status) async {
    await _client.from('orders').update({'status': status}).eq('id', orderId);
  }
}
