import 'package:equatable/equatable.dart';
import 'order_status.dart';
import 'product_model.dart';

/// Maps an order_items row joined as:
/// *, variant:product_variants(*, product:products(*))
class OrderItem extends Equatable {
  final String variantId;
  final String productName;
  final String size;
  final int quantity;
  final double unitPrice;
  // Resolved from variant.product join — may be null if product was deleted
  final ProductModel? product;

  const OrderItem({
    required this.variantId,
    required this.productName,
    required this.size,
    required this.quantity,
    required this.unitPrice,
    this.product,
  });

  Map<String, dynamic> toMap() => {
        'variant_id': variantId,
        'product_name': productName,
        'size': size,
        'quantity': quantity,
        'unit_price': unitPrice,
      };

  factory OrderItem.fromMap(Map<String, dynamic> map) {
    // variant is joined as product_variants row; product nested inside it
    final variantMap = map['variant'] as Map<String, dynamic>?;
    ProductModel? product;
    if (variantMap != null) {
      final productMap = variantMap['product'] as Map<String, dynamic>?;
      product = productMap != null ? ProductModel.fromMap(productMap) : null;
    }

    return OrderItem(
      variantId: map['variant_id'] ?? '',
      productName: map['product_name'] ?? '',
      size: map['size'] ?? '',
      quantity: map['quantity'] ?? 1,
      unitPrice: (map['unit_price'] ?? 0).toDouble(),
      product: product,
    );
  }

  @override
  List<Object?> get props =>
      [variantId, productName, size, quantity, unitPrice, product];
}

class OrderModel extends Equatable {
  final String id;
  final String userId;
  final List<OrderItem> items;
  final double subtotal;
  final double shippingFee;
  final double total;
  final OrderStatus status;
  // Stored inside shipping_address jsonb on the orders table
  final String? address;
  final double? latitude;
  final double? longitude;
  final String? note;
  final double? discountAmount;
  final DateTime createdAt;
  final DateTime? updatedAt;

  const OrderModel({
    required this.id,
    required this.userId,
    required this.items,
    required this.subtotal,
    this.shippingFee = 0,
    required this.total,
    this.status = OrderStatus.pending,
    this.address,
    this.latitude,
    this.longitude,
    this.note,
    this.discountAmount,
    required this.createdAt,
    this.updatedAt,
  });

  /// Insert map for the orders table.
  /// shipping_address is stored as a jsonb object.
  /// order_number is auto-generated by DB — do NOT include it.
  /// created_at / updated_at are managed by DB — do NOT include them.
  Map<String, dynamic> toMap() => {
        'id': id,
        'user_id': userId,
        'status': status.name,
        'shipping_address': {
          'address': address,
          'latitude': latitude,
          'longitude': longitude,
        },
        'shipping_fee': shippingFee,
        'subtotal': subtotal,
        'discount_amount': discountAmount ?? 0,
        'total': total,
        'notes': note,
      };

  factory OrderModel.fromMap(Map<String, dynamic> map) {
    // shipping_address is a jsonb map stored in the orders row
    final shippingAddress = map['shipping_address'] as Map<String, dynamic>?;

    return OrderModel(
      id: map['id'] ?? '',
      userId: map['user_id'] ?? '',
      items: (map['items'] as List?)
              ?.map((e) => OrderItem.fromMap(e as Map<String, dynamic>))
              .toList() ??
          [],
      subtotal: (map['subtotal'] ?? 0).toDouble(),
      shippingFee: (map['shipping_fee'] ?? 0).toDouble(),
      total: (map['total'] ?? 0).toDouble(),
      status: OrderStatus.values.firstWhere(
        (e) => e.name == map['status'],
        orElse: () => OrderStatus.pending,
      ),
      address: shippingAddress?['address'] as String?,
      latitude: (shippingAddress?['latitude'] as num?)?.toDouble(),
      longitude: (shippingAddress?['longitude'] as num?)?.toDouble(),
      note: map['notes'] as String?,
      discountAmount: (map['discount_amount'] as num?)?.toDouble(),
      createdAt: DateTime.tryParse(map['created_at'] ?? '') ?? DateTime.now(),
      updatedAt: map['updated_at'] != null
          ? DateTime.tryParse(map['updated_at'] as String)
          : null,
    );
  }

  OrderModel copyWith({OrderStatus? status}) => OrderModel(
        id: id,
        userId: userId,
        items: items,
        subtotal: subtotal,
        shippingFee: shippingFee,
        total: total,
        status: status ?? this.status,
        address: address,
        latitude: latitude,
        longitude: longitude,
        note: note,
        discountAmount: discountAmount,
        createdAt: createdAt,
        updatedAt: updatedAt,
      );

  @override
  List<Object?> get props => [
        id,
        userId,
        items,
        subtotal,
        shippingFee,
        total,
        status,
        address,
        latitude,
        longitude,
        note,
        discountAmount,
        createdAt,
        updatedAt,
      ];
}
